### ISSUE TITLE
Welp, Non-functional

### ISSUE THREAD

**Issue by daephx** [emmauss/HPXDroid#1]
When the app boots it shows the splash screen and just hangs there.

![](https://i.imgur.com/DRf9C0R.jpg)

**Comment by emmauss** [comment]
This is pretty much wip. I have not yet pushed fixes for this and others.

**Comment by daephx** [comment]
Understandable, just letting you know. 

Edit:
If it's helpful my phone model is "Samsung Galaxy S7 Active SM-G891A"
